name: Release and deploy my golang app

on:
  push:
    branches:
    - "v[0-9]+.[0-9]+"

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
       ref: ${{ github.ref_name }}

    - name: installing railway cli
      run: npm i -g @railway/cli

    - name: deploying railway
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAYTOKEN }}
    - name: Send custom JSON info to the Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Workshop Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Name:\nKaung Htet Win"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Metriculation:\nA0265069W"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Email:\nkaunghtetwynn@gmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Repository:\nhttps://github.com/KaungHtetWynn/MyGolangApp"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Deployment:\nhttps://roomy-place-production.up.railway.app"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://roomy-place-production.up.railway.app/|Open Application>"
                }
              }
            ]
          }
  
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACKSECRET }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK